name: Greet Everybody
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: ./hello-world-action
      - run: echo "hello" >> ./tmp.txt
      - run: cat ./tmp.txt
