name: Greet Everybody
on: [pull_request]

jobs:
  build:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: 'test-label'
