name: Greet Everybody
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # - uses: ./hello-world-action
      - run: npm i
      - run: npm start ${{ secrets.GITHUB_TOKEN }}
