name: Greet Everybody
on: [pull_request]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          repo: '${{ secrets.GITHUB_TOKEN }}'
          label: 'test-label'
