name: Greet Everybody
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: ./hello-world-action
      - run: |
          git checkout -b test
          echo "# Hello" > tmp.md
          git add tmp.md
          git push origin test
